name: Deploy dyln/vercel/* folders to Vercel (changed only)

on:
  push:
    branches: [ main ]
    paths:
      - 'dyln/vercel/**'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect changed backlink folders
        id: collect
        shell: bash
        run: |
          set -euo pipefail

          ROOT="dyln/vercel"
          EVENT="$GITHUB_EVENT_PATH"

          echo "Reading changed files from push payload: $EVENT"
          # from push payload (added / modified / renamed)
          mapfile -t CHANGED < <(
            jq -r '
              [
                (.commits[].added[]?),
                (.commits[].modified[]?),
                (.commits[].renamed[]?.to?),
                (.commits[].renamed[]?.from?)
              ] | unique[]' "$EVENT" \
            | grep -E "^${ROOT}/" || true
          )

          echo "Changed paths under ${ROOT}/:"
          if ((${#CHANGED[@]})); then
            printf '  - %s\n' "${CHANGED[@]}"
          else
            echo "  (none from payload; falling back to listing all under ${ROOT}/)"
          fi

          # Fallback: when triggered manually or payload empty (e.g. GH UI edits)
          if ((${#CHANGED[@]} == 0)); then
            mapfile -t CHANGED < <(git ls-files "${ROOT}/" || true)
          fi

          # Reduce to dyln/vercel/<slug> and require index.html (or Index.html)
          declare -A SEEN=()
          FOLDERS=()
          for p in "${CHANGED[@]}"; do
            [ -z "$p" ] && continue
            folder="$(echo "$p" | cut -d/ -f1-3)"
            [ -z "$folder" ] && continue
            if [ -z "${SEEN[$folder]:-}" ]; then
              if [ -f "$folder/index.html" ] || [ -f "$folder/Index.html" ]; then
                SEEN[$folder]=1
                FOLDERS+=("$folder")
              fi
            fi
          done

          echo "Deployable folders (have index.html):"
          if ((${#FOLDERS[@]})); then
            printf '  - %s\n' "${FOLDERS[@]}"
            json="$(printf '%s\n' "${FOLDERS[@]}" | jq -R . | jq -s '{folder: .}')"
            echo "matrix=$json" >> "$GITHUB_OUTPUT"
          else
            echo "  (none) — emitting __skip__"
            echo 'matrix={"folder":["__skip__"]}' >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      # optional: if deploying to a Team scope
      VERCEL_TEAM_SLUG: ${{ secrets.VERCEL_TEAM_SLUG }}
    steps:
      - uses: actions/checkout@v4

      - name: Skip when no changed folders
        if: matrix.folder == '__skip__'
        run: echo "No dyln/vercel/* folders with index.html changed — skipping."

      - name: Install Vercel CLI & jq
        if: matrix.folder != '__skip__'
        run: |
          npm i -g vercel@latest
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Deploy ${{ matrix.folder }}
        if: matrix.folder != '__skip__'
        shell: bash
        run: |
          set -euo pipefail
          dir="${{ matrix.folder }}"
          project="$(basename "$dir")"
          echo "Deploying: $dir (project: $project)"

          # Normalize case if needed
          [ -f "$dir/Index.html" ] && [ ! -f "$dir/index.html" ] && mv "$dir/Index.html" "$dir/index.html"
          test -f "$dir/index.html" || { echo "Missing $dir/index.html"; exit 1; }

          rm -rf "$dir/.vercel"

          # Force static/no-build behavior
          cat > "$dir/vercel.local.json" <<'JSON'
          { "framework": null, "buildCommand": "", "installCommand": "", "outputDirectory": "." }
          JSON

          if [ -n "${VERCEL_TEAM_SLUG:-}" ]; then
            vercel link --cwd "$dir" --project "$project" --yes \
              --token "$VERCEL_TOKEN" --scope "$VERCEL_TEAM_SLUG"
            vercel deploy --cwd "$dir" --local-config "$dir/vercel.local.json" \
              --prod --yes --token "$VERCEL_TOKEN" --scope "$VERCEL_TEAM_SLUG"
          else
            vercel link --cwd "$dir" --project "$project" --yes --token "$VERCEL_TOKEN"
            vercel deploy --cwd "$dir" --local-config "$dir/vercel.local.json" \
              --prod --yes --token "$VERCEL_TOKEN"
          fi

          echo "✅ Deployed $project"
