name: Deploy dyln/cloudflare to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'cloudflare/**'
  workflow_dispatch:

env:
  CF_PAGES_PROJECT: dyln               # <- your Pages project name
  CF_PAGES_DIR: cloudflare             # <- root folder to publish (contains all backlink subfolders)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wrangler
        run: npm i -g wrangler

      # Create the Pages project if it doesn't exist yet
      - name: Ensure Cloudflare Pages project exists
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -e
          # list existing projects; create if not found
          if ! wrangler pages project list | grep -E "^\s*${CF_PAGES_PROJECT}\b" >/dev/null 2>&1; then
            echo "Creating Pages project ${CF_PAGES_PROJECT}…"
            wrangler pages project create "${CF_PAGES_PROJECT}" --production-branch=main
          else
            echo "Pages project ${CF_PAGES_PROJECT} already exists."
          fi

      # Deploy the folder (all subfolders become routes, e.g. /backlink-001/index.html)
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy "${CF_PAGES_DIR}" \
            --project-name="${CF_PAGES_PROJECT}" \
            --branch=main
