name: Deploy dyln/vercel/* folders to Vercel (changed only)

on:
  push:
    branches: [ main ]
    paths:
      - 'dyln/vercel/**'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2   # ensure previous commit is present for diff

      - id: collect
        shell: bash
        run: |
          set -euo pipefail

          ROOT="dyln/vercel"
          BEFORE="${{ github.event.before }}"
          if [ -n "$BEFORE" ] && [ "$BEFORE" != "0000000000000000000000000000000000000000" ]; then
            CHANGED="$(git diff --name-only "$BEFORE" "${GITHUB_SHA}" -- "$ROOT/**" || true)"
          else
            CHANGED="$(git ls-files "$ROOT/**" || true)"
          fi

          declare -A SEEN=()
          FOLDERS=()
          while IFS= read -r path; do
            [ -z "$path" ] && continue
            # Expect paths like dyln/vercel/<slug>/index.html -> keep first 3 segments
            folder="$(echo "$path" | awk -F/ 'NF>=3 {print $1"/"$2"/"$3}')"
            [ -z "$folder" ] && continue
            if [ -f "$folder/index.html" ] && [ -z "${SEEN[$folder]:-}" ]; then
              SEEN[$folder]=1
              FOLDERS+=("$folder")
            fi
          done <<< "$CHANGED"

          if [ ${#FOLDERS[@]} -eq 0 ]; then
            echo 'matrix={"folder":["__skip__"]}' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          json="$(printf '%s\n' "${FOLDERS[@]}" | jq -R . | jq -s '{folder: .}')"
          echo "matrix=$json" >> "$GITHUB_OUTPUT"

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix || '{"folder":["__skip__"]}') }}
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      # optional if deploying under a team/org
      VERCEL_TEAM_SLUG: ${{ secrets.VERCEL_TEAM_SLUG }}
    steps:
      - uses: actions/checkout@v4

      - name: Skip when no changed folders
        if: matrix.folder == '__skip__'
        run: echo "No dyln/vercel/* folders with index.html changed — skipping."

      - name: Install Vercel CLI & jq
        if: matrix.folder != '__skip__'
        run: |
          npm i -g vercel@latest
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Deploy ${{ matrix.folder }}
        if: matrix.folder != '__skip__'
        shell: bash
        run: |
          set -euo pipefail
          dir="${{ matrix.folder }}"
          project="$(basename "$dir")"   # project is the <slug> folder name
          echo "Deploying: $dir  (project: $project)"

          rm -rf "$dir/.vercel"

          # Force static/no-build behavior
          cat > "$dir/vercel.local.json" <<'JSON'
          {
            "framework": null,
            "buildCommand": "",
            "installCommand": "",
            "outputDirectory": "."
          }
          JSON

          if [ -n "${VERCEL_TEAM_SLUG:-}" ]; then
            vercel link --cwd "$dir" --project "$project" --yes \
              --token "$VERCEL_TOKEN" --scope "$VERCEL_TEAM_SLUG"
            vercel deploy --cwd "$dir" --local-config "$dir/vercel.local.json" \
              --prod --yes --token "$VERCEL_TOKEN" --scope "$VERCEL_TEAM_SLUG"
          else
            vercel link --cwd "$dir" --project "$project" --yes \
              --token "$VERCEL_TOKEN"
            vercel deploy --cwd "$dir" --local-config "$dir/vercel.local.json" \
              --prod --yes --token "$VERCEL_TOKEN"
          fi

          echo "✅ Deployed $project"
