name: Deploy dyln/cloudflare to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "cloudflare/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CF_PAGES_PROJECT: dyln        # choose a name; visible in CF dashboard
      CF_PAGES_DIR: cloudflare            # deploy exactly this folder
    steps:
      - uses: actions/checkout@v4

      - name: Install wrangler
        run: npm i -g wrangler@3

      # Create project if it doesn't exist; safe to run every time
      - name: Ensure Pages project exists
        run: |
          wrangler pages project create "$CF_PAGES_PROJECT" \
            --production-branch=main \
            --framework=none \
            --build-command="" \
            --build-output-directory="$CF_PAGES_DIR" || true

      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy "$CF_PAGES_DIR" --project-name="$CF_PAGES_PROJECT" --branch=main
