name: Deploy dyln/cloudflare to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'cloudflare/**'
  workflow_dispatch:

env:
  CF_PAGES_PROJECT: dyln               # <- your Pages project name
  CF_PAGES_DIR: cloudflare             # <- root folder to publish (contains all backlink subfolders)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wrangler
        run: npm i -g wrangler

      # Check if Pages project exists, create only if missing
      - name: Ensure Cloudflare Pages project exists
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT: ${{ env.CF_PAGES_PROJECT }}
        run: |
          set -e
          if wrangler pages project info "$CF_PAGES_PROJECT" >/dev/null 2>&1; then
            echo "Pages project $CF_PAGES_PROJECT already exists."
          else
            echo "Creating Pages project $CF_PAGES_PROJECT…"
            wrangler pages project create "$CF_PAGES_PROJECT" --production-branch=main
          fi

      # Deploy the folder (all subfolders become routes, e.g. /backlink-001/index.html)
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT: ${{ env.CF_PAGES_PROJECT }}
          CF_PAGES_DIR: ${{ env.CF_PAGES_DIR }}
        run: |
          wrangler pages deploy "$CF_PAGES_DIR" \
            --project-name="$CF_PAGES_PROJECT" \
            --branch=main
